name: Conditional Render Pinger

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Ping Render App (24/7)
        run: |
          echo "Run started at: $(date)"
          DELAY=$((RANDOM % 300 + 300))  # 5–10 min delay
          echo "Sleeping $DELAYs, then pinging..."
          sleep $DELAY
          curl -s https://snakepit-python-portfolio.onrender.com/healthz
