name: Conditional Render Pinger

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Ping Render App (24/7 with 2-4 min delay)
        run: |
          echo "Run started at: $(date)"
          DELAY=$((RANDOM % 120 + 120))
          echo "Sleeping $DELAYs, then pinging..."
          sleep $DELAY
          curl -s https://snakepit-python-portfolio.onrender.com/healthz
